name: CAS CLI - Windows ARM64 smoke test
on:
  workflow_dispatch:

jobs:
  win-arm64:
    runs-on: [self-hosted, Windows, ARM64]  # your own runner labels
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev
          path: git-hist

      - name: Download CAS windows_arm64 artifact
        shell: powershell
        run: |
          Get-ChildItem -Recurse .\exe-arm | Unblock-File

      - name: Run CAS (windows_arm64)
        shell: powershell
        env:
          API_KEY: ${{ secrets.CAS_API_KEY }}
        run: |
          .\exe-arm\cas.exe `
            --api-base-url https://api-viso-ddk8ww8iuhyvvnnq5ayhr4.xdr-qa2-uat.us.paloaltonetworks.com `
            --api-key "$env:API_KEY" `
            --auth-id 4 `
            --repo-id test/may `
            --branch dev `
            --directory "${{ github.workspace }}\git-hist" `
            --source GIT_HOOK `
            --start-commit 74d51d7a11a89e678722ea62b52e908b181dee76
