name: CAS Windows x64

on:
  workflow_dispatch: {}
  push:
    branches: ['**']

jobs:
  win-amd64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true  # pulls real file if cas.tgz is tracked via Git LFS

      - name: Extract cas.tgz
        shell: pwsh
        run: tar -xzf .\cas.tgz

      - name: Unblock files (avoid SmartScreen)
        shell: pwsh
        run: Get-ChildItem -Recurse .\exe* | Unblock-File

      - name: Run CAS
        shell: pwsh
        env:
          CAS_API_KEY: ${{ secrets.CAS_API_KEY }}
        run: >
          .\exe-arm\cas.exe
          --api-base-url https://api-viso-ddk8ww8iuhyvvnnq5ayhr4.xdr-qa2-uat.us.paloaltonetworks.com
          --api-key "$env:CAS_API_KEY"
          --auth-id 4
          --repo-id test/may
          --branch dev
          --directory "${{ github.workspace }}"
          --source GIT_HOOK
          --start-commit 74d51d7a11a89e678722ea62b52e908b181dee76
