name: CAS CLI - Windows x64 smoke test

on:
  workflow_dispatch:
    inputs:
      job_id:
        description: "GitLab job ID that produced the artifact"
        required: true
      artifact_path:
        description: "Path to file inside the job's artifacts"
        required: true
        default: "windows_amd64/build/cas.tgz"
      repo_ref:
        description: "Branch/ref to checkout as the scan directory"
        required: true
        default: "dev"

permissions:
  contents: read

env:
  # Adjust these to your GitLab instance/project
  GITLAB_HOST: "https://gitlab.xdr.pan.local"
  PROJECT: "xdr%2Fcas%2Fcas"   # URL-encoded: xdr/cas/cas -> xdr%2Fcas%2Fcas

jobs:
  win-amd64:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repo to scan (into git-hist)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.repo_ref }}
          path: git-hist

      - name: Download CAS artifact from GitLab (by job ID)
        shell: pwsh
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}   # create this secret with at least read_api
        run: |
          $headers = @{ "PRIVATE-TOKEN" = "$env:GITLAB_TOKEN" }
          $jobId   = "${{ github.event.inputs.job_id }}"
          $apath   = "${{ github.event.inputs.artifact_path }}"
          $url     = "${{ env.GITLAB_HOST }}/api/v4/projects/${{ env.PROJECT }}/jobs/$jobId/artifacts/$apath"
          Write-Host "Downloading: $url"
          Invoke-WebRequest -Headers $headers -Uri $url -OutFile cas.tgz

      - name: Extract cas.tgz
        shell: pwsh
        run: |
          tar -xf cas.tgz
          if (-not (Test-Path .\exe\cas.exe) -and -not (Test-Path .\exe-arm\cas.exe)) {
            Write-Error "cas.exe not found after extraction (expected .\exe\cas.exe or .\exe-arm\cas.exe)."
            exit 1
          }

      - name: Unblock downloaded files (remove Zone.Identifier)
        shell: pwsh
        run: |
          if (Test-Path .\exe)     { Get-ChildItem -Recurse .\exe     | Unblock-File }
          if (Test-Path .\exe-arm) { Get-ChildItem -Recurse .\exe-arm | Unblock-File }

      - name: Sanity check layout
        shell: pwsh
        run: |
          Get-Chi
