name: CAS CLI - Windows x64 smoke test
on:
  workflow_dispatch:

jobs:
  win-amd64:
    runs-on: windows-latest  # Windows Server 2022 x64
    timeout-minutes: 30
    steps:
      - name: Checkout target repo into "git-hist" (branch dev)
        uses: actions/checkout@v4
        with:
          ref: main
          path: git-hist

      - name: Unblock files (remove SmartScreen/Zone.Identifier)
        shell: powershell
        run: |
          Get-ChildItem -Recurse .\exe-amd | Unblock-File

      - name: Run CAS (windows_amd64)
        shell: powershell
        env:
          API_KEY: ${{ secrets.CAS_API_KEY }}
        run: |
          Set-StrictMode -Version Latest
          .\exe-amd\cas.exe `
            --api-base-url https://api-viso-ddk8ww8iuhyvvnnq5ayhr4.xdr-qa2-uat.us.paloaltonetworks.com `
            --api-key "$env:API_KEY" `
            --auth-id 4 `
            --repo-id test/may `
            --branch dev `
            --directory "${{ github.workspace }}\git-hist" `
            --source GIT_HOOK `
            --start-commit 74d51d7a11a89e678722ea62b52e908b181dee76
